#!/bin/bash

PKG_NAME="privoxy"
INST_DIR="/tmp/_${PKG_NAME}"
PKG_DIR="/tmp/_${PKG_NAME}_pkg"
PKG_DEST="/image/packages"

PrepareDirs() {
    for dir in $INST_DIR $PKG_DIR; do
        rm -rf "$dir"
    done
    for dir in $INST_DIR $PKG_DIR $PKG_DEST; do
        mkdir -p "$dir"
    done
}

SetupPackageFiles() {
    make install

    echo SynoBuildConf/install: removing man files
    rm -fr $INST_DIR/share/man

    echo SynoBuildConf/install: Re-rewriting config
    sed -E -e 's+^#?confdir .*+confdir /var/packages/privoxy/etc+' \
           -e 's+^#?logdir .*+logdir /var/packages/privoxy/target/var/log/privoxy+' \
           -e 's+^#?user-manual .*+user-manual /var/packages/privoxy/target/share/doc/privoxy/user-manual+' \
           -e 's+^#?enable-remote-toggle .*+enable-remote-toggle  1+' \
           -e 's+^#?enable-edit-actions .*+enable-edit-actions 1+' \
           $INST_DIR/etc/config >$INST_DIR/etc/config.tmp
    mv $INST_DIR/etc/config.tmp $INST_DIR/etc/config
    chmod 0660 $INST_DIR/etc/config

    install -D -t $INST_DIR/port_conf synology/port_conf/privoxy.sc
    mkdir $INST_DIR/ui
    install -D -t $INST_DIR/ui synology/ui/*
    mkdir $INST_DIR/ui/images
    install -D -t $INST_DIR/ui/images synology/ui/images/*

    synology/INFO.sh > INFO
    cp INFO "${PKG_DIR}"
    cp -r synology/scripts/ "${PKG_DIR}"
    cp -r synology/conf/ "${PKG_DIR}"
    cp -r synology/WIZARD_UIFILES/ "${PKG_DIR}"
    cp synology/PACKAGE_ICON{,_256}.PNG "${PKG_DIR}"
}

MakePackage() {
    source /pkgscripts/include/pkg_util.sh
    pkg_make_package $INST_DIR $PKG_DIR
    pkg_make_spk $PKG_DIR $PKG_DEST
}

main() {
    PrepareDirs
    SetupPackageFiles
    MakePackage 
}

main "$@"
