#!/bin/bash

PKG_NAME="privoxy"
INST_DIR="/tmp/_${PKG_NAME}"
PKG_DIR="/tmp/_${PKG_NAME}_pkg"
PKG_DEST="/image/packages"

PrepareDirs() {
    for dir in $INST_DIR $PKG_DIR; do
        rm -rf "$dir"
    done
    for dir in $INST_DIR $PKG_DIR $PKG_DEST; do
        mkdir -p "$dir"
    done
}

SetupPackageFiles() {
    # workaround for missing command groups
    PATH=$PATH:/source/$PKG_NAME/SynoBuildConf/bin 

    make install

    echo SynoBuildConf/install: removing man files
    rm -fr $INST_DIR/share/man

    echo SynoBuildConf/install: Re-rewriting config
    sed -E -i -e 's+^#?confdir .*+confdir /var/packages/privoxy/etc+' \
              -e 's+^#?logdir .*+logdir /var/packages/privoxy/var+' \
              -e 's+^#?user-manual .*+user-manual /var/packages/privoxy/target/share/doc/privoxy/user-manual+' \
              -e 's+^#?enable-remote-toggle .*+enable-remote-toggle  1+' \
              -e 's+^#?enable-edit-actions .*+enable-edit-actions 1+' \
              $INST_DIR/etc/config
    chmod 0660 $INST_DIR/etc/config

    echo SynoBuildConf/install: Adding DSM specific dirs
    install -D -m 0644 -t $INST_DIR/port_conf synology/port_conf/$PKG_NAME.sc
    mkdir $INST_DIR/ui
    install -D -m 0644 -t $INST_DIR/ui synology/ui/config
    install -D -m 0755 -t $INST_DIR/ui synology/ui/*.cgi
    mkdir $INST_DIR/ui/images
    install -D -m 0644 -t $INST_DIR/ui/images synology/ui/images/*

    echo SynoBuildConf/install: Adding DSM packaging files
    synology/INFO.sh > INFO
    cp INFO "${PKG_DIR}"
    cp -r synology/scripts/ "${PKG_DIR}"
    cp -r synology/conf/ "${PKG_DIR}"
    #cp -r synology/WIZARD_UIFILES/ "${PKG_DIR}" #wizard todo
    cp synology/PACKAGE_ICON{,_256}.PNG "${PKG_DIR}"
}

MakePackage() {
    source /pkgscripts-ng/include/pkg_util.sh
    pkg_make_package $INST_DIR $PKG_DIR
    pkg_make_spk $PKG_DIR $PKG_DEST $(pkg_get_spk_family_name)
}

main() {
    PrepareDirs
    SetupPackageFiles
    MakePackage 
}

main "$@"
