#!/bin/sh
# Copyright (c) 2018-2021 David Cavallini
#    This file is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    It is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this file.  If not, see <http://www.gnu.org/licenses/>.

# Package
PACKAGE="privoxy"
DNAME="Privoxy"

# Others
INSTALL_DIR="/var/packages/$PACKAGE/target"
CFG_DIR="/var/packages/$PACKAGE"
PATH="${INSTALL_DIR}/sbin:${PATH}"
CMD="${INSTALL_DIR}/sbin/privoxy"
CFG_FILE="${CFG_DIR}/etc/config"
PID_FILE="${CFG_DIR}/var/${PACKAGE}.pid"
LOG_FILE="${CFG_DIR}/var/logfile"
SYSTEMD_SVC=pkguser-privoxydsm

start_daemon ()
{
    #${CMD} --pidfile ${PID_FILE} ${CFG_FILE}

    synosystemctl start $SYSTEMD_SVC

    warn_if_cgi_not_root
}

stop_daemon ()
{
    synosystemctl stop $SYSTEMD_SVC
}

daemon_status ()
{
    #unfortunately there is no synosystemctl status, so check with the PID file
    if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" > /dev/null 2>&1; then
        return 0
    else
        rm -f "$PID_FILE"
        return 1
    fi
}

warn_if_cgi_not_root ()
{
    if [ ! "$(stat -c %u "$INSTALL_DIR/ui/index.cgi")" = "0" ]; then
        echo "Privoxy DSM misses privileges allowing to access the web admin interface. If you need it, connect though SSH, run the following command and restart: sudo /var/packages/privoxy/scripts/addprivileges" >> "$SYNOPKG_TEMP_LOGFILE"
    fi
}

case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
        else
            echo Starting ${DNAME} ...
            start_daemon
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
        else
            echo ${DNAME} is not running
        fi
        ;;
    status)
        if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    log)
        echo ${LOG_FILE}
        ;;
    *)
        exit 1
        ;;
esac
