#!/bin/sh
# Copyright (c) 2018 David Cavallini
#    This file is part of synology-dsm.
#
#    synology-dsm is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    synology-dsm is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with synology-dsm.  If not, see <http://www.gnu.org/licenses/>.

# Package
PACKAGE="privoxy"
DNAME="privoxy"

# Others
INSTALL_DIR="/var/packages/privoxy/target"
CFG_DIR="/var/packages/privoxy"
PATH="${INSTALL_DIR}/sbin:${PATH}"
CMD="${INSTALL_DIR}/sbin/privoxy"
CFG_FILE="${CFG_DIR}/etc/config"
PID_FILE="${INSTALL_DIR}/var/run/${PACKAGE}.pid"
LOG_FILE="${INSTALL_DIR}/var/log/privoxy/logfile"

start_daemon ()
{
    #No need to su as start is already called with privoxy user
    ${CMD} --pidfile ${PID_FILE} ${CFG_FILE}
}

stop_daemon ()
{
    kill `cat ${PID_FILE}`
    wait_for_status 1 20 || kill -9 `cat ${PID_FILE}`
    rm -f ${PID_FILE}
}

daemon_status ()
{
    if [ -f ${PID_FILE} ] && kill -0 `cat ${PID_FILE}` > /dev/null 2>&1; then
        return
    fi
    rm -f ${PID_FILE}
    return 1
}

wait_for_status ()
{
    counter=$2
    while [ ${counter} -gt 0 ]; do
        daemon_status
        [ $? -eq $1 ] && return
        let counter=counter-1
        sleep 1
    done
    return 1
}

case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
        else
            echo Starting ${DNAME} ...
            start_daemon
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
        else
            echo ${DNAME} is not running
        fi
        ;;
    status)
        if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    log)
        echo ${LOG_FILE}
        ;;
    *)
        exit 1
        ;;
esac
